export const Top = [
  "Hat",
  "NoHair",
  "Eyepatch",
  "Hijab",
  "Turban",
  "WinterHat1",
  "WinterHat2",
  "WinterHat3",
  "WinterHat4",
  "LongHairBigHair",
  "LongHairBob",
  "LongHairBun",
  "LongHairCurly",
  "LongHairCurvy",
  "LongHairDreads",
  "LongHairFrida",
  "LongHairFro",
  "LongHairFroBand",
  "LongHairNotTooLong",
  "LongHairShavedSides",
  "LongHairMiaWallace",
  "LongHairStraight",
  "LongHairStraight2",
  "LongHairStraightStrand",
  "ShortHairDreads01",
  "ShortHairDreads02",
  "ShortHairFrizzle",
  "ShortHairShaggy",
  "ShortHairShaggyMullet",
  "ShortHairShortCurly",
  "ShortHairShortFlat",
  "ShortHairShortRound",
  "ShortHairShortWaved",
  "ShortHairSides",
  "ShortHairTheCaesar",
  "ShortHairTheCaesarSidePart",
];

export const HairColor = [
  "#A55728",
  "#2C1B18",
  "#B58143",
  "#D6B370",
  "#724133",
  "#4A312C",
  "#F59797",
  "#000fdb",
  "#ECDCBF",
  "#C93305",
  "#E8E1E1",
];

export const HairColorKeys = [
  "Auburn",
  "Black",
  "Blonde",
  "BlondeGolden",
  "Brown",
  "BrownDark",
  "PastelPink",
  "Blue",
  "Platinum",
  "Red",
  "SilverGray",
];

export const Accessories = [
  "Prescription01",
  "Blank",
  "Kurt",
  "Prescription02",
  "Round",
  "Sunglasses",
  "Wayfarers",
];

export const FacialHair = [
  "BeardLight",
  "Blank",
  "BeardMedium",
  "BeardMajestic",
  "MoustacheFancy",
  "MoustacheMagnum",
];

export const Eyebrows = [
  "DefaultNatural",
  "Angry",
  "AngryNatural",
  "Default",
  "FlatNatural",
  "RaisedExcited",
  "RaisedExcitedNatural",
  "SadConcerned",
  "SadConcernedNatural",
  "UnibrowNatural",
  "UpDown",
  "UpDownNatural",
];

export const Eyes = [
  "Happy",
  "Close",
  "Cry",
  "Default",
  "Dizzy",
  "EyeRoll",
  "Hearts",
  "Side",
  "Squint",
  "Surprised",
  "Wink",
  "WinkWacky",
];

export const Mouth = [
  "Smile",
  "Concerned",
  "Default",
  "Disbelief",
  "Eating",
  "Grimace",
  "Sad",
  "ScreamOpen",
  "Serious",
  "Tongue",
  "Twinkle",
  "Vomit",
];

export const Clothes = [
  "BlazerShirt",
  "BlazerSweater",
  "CollarSweater",
  "GraphicShirt",
  "Hoodie",
  "Overall",
  "ShirtCrewNeck",
  "ShirtScoopNeck",
  "ShirtVNeck",
];

export const ClothesColorKeys = [
  "Black",
  "Blue01",
  "Blue02",
  "Blue03",
  "Gray01",
  "Gray02",
  "Heather",
  "PastelBlue",
  "PastelGreen",
  "PastelOrange",
  "PastelRed",
  "PastelYellow",
  "Pink",
  "Red",
  "White",
];

export const ClothesColor = [
  "#262E33",
  "#65C9FF",
  "#5199E4",
  "#25557C",
  "#E6E6E6",
  "#929598",
  "#3C4F5C",
  "#B1E2FF",
  "#A7FFC4",
  "#FFDEB5",
  "#FFAFB9",
  "#FFFFB1",
  "#FF488E",
  "#FF5C5C",
  "#FFFFFF",
];

export const Skin = [
  "Light",
  "Tanned",
  "Yellow",
  "Pale",
  "Brown",
  "DarkBrown",
  "Black",
];
